eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
    
feign:
  hystrix:
    enabled: true
management:
   endpoints:     
    web:
      exposure:
        include: hystrix.stream
---
spring:
  profiles: order1
  cloud:
    config:
      override-none: true
  rabbitmq:
    host: 192.168.88.128
    port: 15672
    username: admin
    password: admin
  
server:
  port: 8201 
---
spring:
  profiles: order2
  cloud:
    config:
      override-none: true
  rabbitmq:
    host: 192.168.88.128
    port: 5672
    username: admin
    password: admin
server:
  port: 8202 

